### ISSUE TITLE
Tesseract not found command error

### ISSUE THREAD

**Issue by JDoe21** [maxenxe/HQ-Trivia-Bot#1]
PS C:\Users\M\Downloads\HQ-Trivia-Bot-master\HQ-Trivia-Bot-master> node bot.js
Screenshot done
Answers resized
node-tesseract: Running 'tesseract answers.jpg C:\Users\M\AppData\Local\Temp\tmp-7636ymymjBsOSTW9'
node-tesseract: Preprocessor cleanup
{ Error: Command failed: tesseract answers.jpg C:\Users\M\AppData\Local\Temp\tmp-7636ymymjBsOSTW9
Der Befehl "tesseract" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'tesseract answers.jpg C:\\Users\\M\\AppData\\Local\\Temp\\tmp-7636ymymjBsOSTW9' }

**Comment by maxenxe** [comment]
try reinstalling tesseract by executing `npm install nodecr` , if it doesn't work verify that tesseract is in the PATH field of your environment variables (Open Control Panel » System » Advanced » Environment Variables)

**Comment by maxenxe** [comment]
Don't forget to tell me if it fixed the problem so I can close the issue 😄

**Comment by JDoe21** [comment]
yeah fixed ty

**Comment by tdaddy** [comment]
do you use tesseract as the variable name when adding the path to environment variables?

**Comment by maxenxe** [comment]
no, you just add the path to PATH, so you modify PATH, you add a ; at the end of the PATH, and then the tesseract path without the file 
( not your/path/tesseract.exe but your/path/)
