### ISSUE TITLE
Giving a link and not an answer?

### ISSUE THREAD

**Issue by lampkiller44** [maxenxe/HQ-Trivia-Bot#10]
Screenshot done
Answers resized
node-tesseract: Running 'tesseract answers.jpg C:\Users\Lamp\AppData\Local\Temp\tmp-21400xtOHIKD8Cz0'
node-tesseract: Deleting 'C:\Users\Lamp\AppData\Local\Temp\tmp-21400xtOHIKD8Cz0.txt'
node-tesseract: Preprocessor cleanup
DookS?
- hC
Rian Johnson arve
J.J. Abrams srre

Question resized
node-tesseract: Running 'tesseract question.jpg C:\Users\Lamp\AppData\Local\Temp\tmp-2140ZHZTL5sCUImq'
node-tesseract: Deleting 'C:\Users\Lamp\AppData\Local\Temp\tmp-2140ZHZTL5sCUImq.txt'
node-tesseract: Preprocessor cleanup
The question is "P  Which Sci—Fi film/TV creator has written X—Men comic books? "
Wikipedia link found: https://en.wikipedia.org/wiki/X-Men
Wikipedia link found: https://en.wikipedia.org/wiki/Stan_Lee
Wikipedia link found: https://en.wikipedia.org/wiki/J._Michael_Straczynski
Wikipedia link found: https://en.wikipedia.org/wiki/Warren_Ellis
Wikipedia link found: https://en.wikipedia.org/wiki/Chris_Claremont
Wikipedia link found: https://en.wikipedia.org/wiki/X-Men:_First_Class
Wikipedia link found: https://en.wikipedia.org/wiki/X-Men:_Days_of_Future_Past
Wikipedia link found: https://en.wikipedia.org/wiki/Superhero_fiction

**Comment by maxenxe** [comment]
If you look at the question and the answers in your message, you'll see that they aren't resized correctly, you should change the coordinates in the code

**Comment by lampkiller44** [comment]
Ok thank you
