### ISSUE TITLE
res.links error?

### ISSUE THREAD

**Issue by lampkiller44** [maxenxe/HQ-Trivia-Bot#13]
> node bot.js

Screenshot done
Answers resized
node-tesseract: Running 'tesseract answers.jpg C:\Users\Lamp\AppData\Local\Temp\tmp-7368w24GCZrIGEM7'
node-tesseract: Deleting 'C:\Users\Lamp\AppData\Local\Temp\tmp-7368w24GCZrIGEM7.txt'
node-tesseract: Preprocessor cleanup
Straw—capping
Panhandling

Question resized
node-tesseract: Running 'tesseract question.jpg C:\Users\Lamp\AppData\Local\Temp\tmp-7368AHsTmZJKZqpp'
node-tesseract: Deleting 'C:\Users\Lamp\AppData\Local\Temp\tmp-7368AHsTmZJKZqpp.txt'
node-tesseract: Preprocessor cleanup
The question is "Vhat is the act C performing music public places for ti "
Error: Error on response (503):null : <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head><meta http-equiv="content-type" content="text/html; charset=utf-8"><meta name="viewport" content="initial-scale=1"><title>https://www.google.com/search?hl=en&amp;q=Vhat%20is%20the%20act%20C%20performing%20music%20public%20places%20for%20ti%20%0C&amp;start=0&amp;sa=N&amp;num=25&amp;ie=UTF-8&amp;oe=UTF-8&amp;gws_rd=ssl</title></head>
<body style="font-family: arial, sans-serif; background-color: #fff; color: #000; padding:20px; font-size:18px;" onload="e=document.getElementById('captcha');if(e){e.focus();}">
<div style="max-width:400px;">
<hr noshade size="1" style="color:#ccc; background-color:#ccc;"><br>
<form action="index" method="post">
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
<div id="recaptcha" class="g-recaptcha" data-sitekey="6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b"></div>
<input type='hidden' name='q' value='EgREMD8UGLzTkdUFIhkA8aeDSxzfcvmotxa2U8DeUDSbaku4OvoGMgFy'><input type="hidden" name="continue" value="https://www.google.com/search?hl=en&amp;q=Vhat%20is%20the%20act%20C%20performing%20music%20public%20places%20for%20ti%20%0C&amp;start=0&amp;sa=N&amp;num=25&amp;ie=UTF-8&amp;oe=UTF-8&amp;gws_rd=ssl">
<input type="submit" name="submit" value="Submit" style="font-size:18px; padding:4px 0;"><br><br><br>
</form>
<hr noshade size="1" style="color:#ccc; background-color:#ccc;">

<div style="font-size:13px;">
<b>About this page</b><br><br>Our systems have detected unusual traffic from your computer network.  This page checks to see if it&#39;s really you sending the requests, and not a robot.  <a href="#" onclick="document.getElementById('infoDiv').style.display='block';">Why did this happen?</a><br><br>
<div id="infoDiv" style="display:none; background-color:#eee; padding:10px; margin:0 0 15px 0; line-height:1.4em;">
This page appears when Google automatically detects requests coming from your computer network which appear to be in violation of the <a href="//www.google.com/policies/terms/">Terms of Service</a>. The block will expire shortly after those requests stop.  In the meantime, solving the above CAPTCHA will let you continue to use our services.<br><br>This traffic may have been sent by malicious software, a browser plug-in, or a script that sends automated requests.  If you share your network connection, ask your administrator for help &mdash; a different computer using the same IP address may be responsible.  <a href="//support.google.com/websearch/answer/86640">Learn more</a><br><br>Sometimes you may be asked to solve the CAPTCHA if you are using advanced terms that robots are known to use, or sending requests very quickly.
</div>

IP address: <br>Time: 2018-03-10T23:26:52Z<br>URL: https://www.google.com/search?hl=en&amp;q=Vhat%20is%20the%20act%20C%20performing%20music%20public%20places%20for%20ti%20%0C&amp;start=0&amp;sa=N&amp;num=25&amp;ie=UTF-8&amp;oe=UTF-8&amp;gws_rd=ssl<br>
</div>
</div>
</body>
</html>

    at Request._callback (C:\Users\Lamp\Desktop\HQ-Trivia-Bot-master\node_modules\google\lib\google.js:98:16)
    at Request.self.callback (C:\Users\Lamp\Desktop\HQ-Trivia-Bot-master\node_modules\request\request.js:186:22)
    at Request.emit (events.js:180:13)
    at Request.<anonymous> (C:\Users\Lamp\Desktop\HQ-Trivia-Bot-master\node_modules\request\request.js:1163:10)
    at Request.emit (events.js:180:13)
    at IncomingMessage.<anonymous> (C:\Users\Lamp\Desktop\HQ-Trivia-Bot-master\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:272:13)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:114:19)
C:\Users\Lamp\Desktop\HQ-Trivia-Bot-master\bot.js:50
                              for (var i = 0; i < res.links.length; ++i) {
                                                      ^

TypeError: Cannot read property 'links' of null
    at C:\Users\Lamp\Desktop\HQ-Trivia-Bot-master\bot.js:50:55
    at Request._callback (C:\Users\Lamp\Desktop\HQ-Trivia-Bot-master\node_modules\google\lib\google.js:98:7)
    at Request.self.callback (C:\Users\Lamp\Desktop\HQ-Trivia-Bot-master\node_modules\request\request.js:186:22)
    at Request.emit (events.js:180:13)
    at Request.<anonymous> (C:\Users\Lamp\Desktop\HQ-Trivia-Bot-master\node_modules\request\request.js:1163:10)
    at Request.emit (events.js:180:13)
    at IncomingMessage.<anonymous> (C:\Users\Lamp\Desktop\HQ-Trivia-Bot-master\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:272:13)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1101:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hqtriviabot@1.0.0 start: `node bot.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hqtriviabot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lamp\AppData\Roaming\npm-cache\_logs\2018-03-10T23_26_51_876Z-debug.log

**Comment by maxenxe** [comment]
Try using a VPN for the Google error, it should fix the problem
