### ISSUE TITLE
npm WARN hqtriviabot@1.0.0 No repository field

### ISSUE THREAD

**Issue by yapal** [maxenxe/HQ-Trivia-Bot#16]
$ npm install
npm WARN hqtriviabot@1.0.0 No repository field.

up to date in 1.514s

IS this ERROR?

**Comment by yapal** [comment]
$ node bot.js
Screenshot done
{ Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:330:11)
    at Object.exports.spawn (child_process.js:500:9)
    at spawn (C:\HQ-Trivia-Bot\node_modules\cross-spawn\index.js:17:18)
    at gm._spawn (C:\HQ-Trivia-Bot\node_modules\gm\lib\command.js:224:14)
    at C:\HQ-Trivia-Bot\node_modules\gm\lib\command.js:101:12
    at series (C:\HQ-Trivia-Bot\node_modules\array-series\index.js:11:36)
    at gm._preprocess (C:\HQ-Trivia-Bot\node_modules\gm\lib\command.js:177:5)
    at gm.write (C:\HQ-Trivia-Bot\node_modules\gm\lib\command.js:99:10)
    at Object.callback (C:\HQ-Trivia-Bot\bot.js:20:12)
    at Jimp.handleCallback (C:\HQ-Trivia-Bot\node_modules\desktop-screenshot\module.js
:38:11) errno: 'UNKNOWN', code: 'UNKNOWN', syscall: 'spawn' }

i got this error. im using windows 7 (32 bit). i used this on screenshot. done everything as described in readme. Path variable is set and here it is: 

c:\program files\graphicsmagick-1.3.28-q16;C:\Python36\Scripts\;C:\Python36\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd\;C:\Program Files\Tesseract-OCR\;C:\Program Files\nodejs\;C:\Program Files\Tesseract-OCR\tessdata\;

plz reply bro

**Comment by maxenxe** [comment]
Try updating node and your modules

**Comment by yapal** [comment]
npm version=5.7.1
node version=8.10.0
when i bash going to HQ-Trivia_Bot directory and run "npm-check-updates" it results in:

C:\HQ-Trivia-Bot>npm-check-updates
[INFO]: You can also use ncu as an alias
Using C:\HQ-Trivia-Bot\package.json
[..................] / :
All dependencies match the latest package versions :)

THEN WHEN I RUN node bot.js IT RESULTS IN:

C:\HQ-Trivia-Bot>node bot.js
Screenshot done
{ Error: spawn UNKNOWN
    at _errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at Object.exports.spawn (child_process.js:502:9)
    at spawn (C:\HQ-Trivia-Bot\node_modules\cross-spawn\index.js:17:18)
    at gm._spawn (C:\HQ-Trivia-Bot\node_modules\gm\lib\command.js:224:14)
    at C:\HQ-Trivia-Bot\node_modules\gm\lib\command.js:101:12
    at series (C:\HQ-Trivia-Bot\node_modules\array-series\index.js:11:36)
    at gm._preprocess (C:\HQ-Trivia-Bot\node_modules\gm\lib\command.js:177:5)
    at gm.write (C:\HQ-Trivia-Bot\node_modules\gm\lib\command.js:99:10)
    at Object.callback (C:\HQ-Trivia-Bot\bot.js:20:12) code: 'UNKNOWN', errno: '
UNKNOWN', syscall: 'spawn' }

C:\HQ-Trivia-Bot>


plz help MAXENXE bro

**Comment by maxenxe** [comment]
Probably not a problem with my bot, I'll search online

**Comment by yapal** [comment]
Bro any updates regarding that error? I'm on Windows 7

**Comment by yapal** [comment]
Some points I noticed now:
1) wen I look into the bot folder I found screenshot that got saved when I executed program. The screenshot is full screen of desktop. Is that the cause for that error?

2) i placed screenshot that has- question with answers of a quiz game and tried that project by seeing co-ordinates. I dint mirror my phone n ran that program. Is that a cause?

**Comment by maxenxe** [comment]
The bot take a screenshot of your PC and analysis it aha

**Comment by yapal** [comment]
Ya. So is that a problem?

**Comment by maxenxe** [comment]
No but question and answer are made from the screenshot.jpg so you should have at least an hq screenshot opened on your PC with the right coordinate while running the bot

**Comment by yapal** [comment]
I dint mirror my phone. Just tried program on a screenshot by taking it's co-ordinates.

**Comment by yapal** [comment]
Then I made correct. It's on desktop. I took it's co-ordinates too

**Comment by yapal** [comment]
R u using Mac? I'm on Windows. I searched in internet about Spawn UNKNOWN seems like there is issue on Windows. But dint get how to solve it

**Comment by maxenxe** [comment]
No I'm using Windows and you're the first people to have this issue

**Comment by yapal** [comment]
I like ur pic. It's nice. Is that ur pic?

**Comment by yapal** [comment]
Windows 10?

**Comment by yapal** [comment]
See my 1st error msg bro. And see PATH too. Should I add npm in path. If yes how?

**Comment by yapal** [comment]
Im using Windows 7 ultimate. Is there something missing in path? And see very first message that I sent. Is there something wrong?

**Comment by maxenxe** [comment]
Nothing wrong

**Comment by yapal** [comment]
Steps I followed:
1) I installed node in C Drive. It was added to path during installation by default.
2) I done git clone to ur bot address and bot was downloaded in C Drive.
3)i opened cmd in bot folder directory then ran "npm install".
4)placed snapshot on desktop and took it's co-ordinates by the application u mentioned and made changes in bot as u mentioned.
5) then went to hq directory of ur bot ad ran node bot.js(npm start too) but gives that spawn UNKNOWN msg. 
Did I made something wrong in these steps

**Comment by imthebat** [comment]
delete and install modules again

**Comment by nanip9997** [comment]
how to set the coordinates rightly can you explain and it always scrrenshots my desktop screen and not the coordinates I ve specified but how's that possible with the coordinatrs placed and more over a warning like 
npm WARN @HQTriviaBotMaster1.0.0.0 no repository field is showing is that the reason of the bot not working properly??

**Comment by yapal** [comment]
the issue was graphicmagic was installed with 64 bit but im running 32 bot
