### ISSUE TITLE
Unknown Error pls help

### ISSUE THREAD

**Issue by DX47** [maxenxe/HQ-Trivia-Bot#17]
![image](https://user-images.githubusercontent.com/36262105/37556644-ec7404d2-2a09-11e8-98a3-1e5b756e6dd3.png)
please refer to the image 
it was working fine suddenly it appeared

**Comment by DX47** [comment]
this is the log 
![image](https://user-images.githubusercontent.com/36262105/37557178-c57d64a6-2a11-11e8-8056-3a1972648a17.png)
pls help

**Comment by DX47** [comment]
it was working just fine and suddenly this error . i really appreciate ur work . HELP NEEDED!!!!!!!

**Comment by maxenxe** [comment]
And what happens if you simply write `node bot.js` instead of `npm start` ?

**Comment by ZTW21** [comment]
I have the same problem, this is what shows up

![capture](https://user-images.githubusercontent.com/37523643/37575113-d7a677ae-2afb-11e8-999b-5021a8b37028.PNG)

**Comment by DX47** [comment]
Its the sameee plss help brooo

**Comment by DX47** [comment]
I swear it worked 100% perfect then suddenly 😫

**Comment by maxenxe** [comment]
Can you copy paste the message you get in cmd, not the log just the error

**Comment by DX47** [comment]
Its the first pic right ? Ok still ill give a new one .

**Comment by DX47** [comment]
Whats the time there cause its 12:00 am here 😶😕

**Comment by maxenxe** [comment]
Yep but I don't have the firsts lines in the first pic, and I think the key of the error is there

**Comment by DX47** [comment]
Ok ill give u the wholeee thing 👍. Are u going to close this project

**Comment by DX47** [comment]
Can i tell u tom . im gonna sleep rn.

**Comment by maxenxe** [comment]
It's 21:40, 9:40 PM aha
No problem for tommorow

**Comment by DX47** [comment]
hey bro
![image](https://user-images.githubusercontent.com/36262105/37657990-7ea66818-2c5d-11e8-8582-33b69d0319a7.png)
if i type node bot.js then its not coming (ty for that) and now this error pops up helppp!!!!!!!!!!!
and the answer comes like this 
![image](https://user-images.githubusercontent.com/36262105/37658135-e4f26202-2c5d-11e8-81e0-9e9f5c9a0843.png)
mannn!! ur bot worked reallly well until this came and was accurate too

**Comment by DX47** [comment]
and sometimes the answers come in unidentified letters and answers come in links (sometimes).
sry for all of this but.... ( hope u understand). XDD

**Comment by DX47** [comment]
Brooo?

**Comment by DX47** [comment]
?

**Comment by Allmight3** [comment]
![error](https://user-images.githubusercontent.com/35853584/37738469-5bc4b31a-2d14-11e8-89bf-bc65e32d1da4.png)

I'm also consistently getting that error. OCR works, then it finds a wikipedia article and links that. Then every single time it follows with this error and that's the end of it. I'm starting the bot via "node bot.js" since the npm start doesn't work properly.

Can you help us with this error @maxenxe ?

**Comment by maxenxe** [comment]
Yep, my bot is set up in a way that it looks for the 3 answers online, but if your coordinates aren't set up correctly, it will not find the 3 answers with text analysis and that's why you're getting this error, the coordinates are line 19 and 34 in the code

**Comment by Allmight3** [comment]
The coordinates are working fine though. This is easy to tell because I can see it in the question.jpg output as well as the OCR readout: "The question is [OCR HERE]". Then on the next line it repeats the question with a "found!" after the question. Then it lists an appropriately related wikipedia link. Then it throws up all of the toLowerCase errors from the screenshot I sent.

**Comment by maxenxe** [comment]
But are the answers coordinates correct ?

**Comment by maxenxe** [comment]
Does the answers.jpg file contains the answers ?

**Comment by Allmight3** [comment]
Haha, thank you. Now I figured it out.

I misunderstood the directions. I thought we were supposed to copy the same coordinates for line 34 into line 19. Now I realize how it works. Just tested and it is correct. Thanks for the assistance, it's a very useful bot!

**Comment by maxenxe** [comment]
No problem, thanks for your support !

**Comment by DX47** [comment]
Bro maxene my answers.jpg is crct

**Comment by DX47** [comment]
Maxenxe*

**Comment by DX47** [comment]
@maxenxe i am still getting the error pls help
