### ISSUE TITLE
can you please say how to install modules required in the hq bot folder

### ISSUE THREAD

**Issue by nanip9997** [maxenxe/HQ-Trivia-Bot#18]

**Comment by DX47** [comment]
Open command prompt in that folder and in cmd type npm install ( u should first download node.js )

**Comment by DX47** [comment]
Tell me if it helps

**Comment by nanip9997** [comment]
Thanks but I have my node files in C drive but the Hq trivia bot files in E drive and now can you clarify whether it is the command 

E:\User\Hq-Trivia-Botfolder\HqTriviaBot npm install 
Is this the correct way even though I tried it this it says npm command is not either external or internal

**Comment by maxenxe** [comment]
Modify your path variable, look at earlier closed issues for further informations

**Comment by nanip9997** [comment]
Ok maxenxe ! I will try
