### ISSUE TITLE
Error: Cannot find module 'desktop-screenshot'

### ISSUE THREAD

**Issue by ZTW21** [maxenxe/HQ-Trivia-Bot#20]
I keep getting this error, can you point out what is causing this problem?
![capture](https://user-images.githubusercontent.com/37523643/37614911-534c31f6-2b82-11e8-8a38-dd034b167bf3.PNG)
![capture2](https://user-images.githubusercontent.com/37523643/37614926-5b688f2e-2b82-11e8-9164-294e6a8a9cb6.PNG)

Above is what happens when I type "node bot.js" (first) and "npm start" (second)

**Comment by maxenxe** [comment]
`npm install desktop-screenshot`

**Comment by ZTW21** [comment]
I am getting this error now
Error: Command failed: gm convert: Option '-crop' requires an argument or argument is malformed.
![capture3](https://user-images.githubusercontent.com/37523643/37618778-b2e5f56a-2b8d-11e8-88cf-938d0ba8a12e.PNG)

**Comment by maxenxe** [comment]
How are your lines 19 and 34 ?

**Comment by ZTW21** [comment]
![capture4](https://user-images.githubusercontent.com/37523643/37618992-65717a74-2b8e-11e8-9d8a-aca2d3ba7b2a.PNG)

It looks fine to me... Am I doing something wrong?

**Comment by maxenxe** [comment]
actually, you should replace 'top-left-x', etc by the real coordinates from your phone mirrored to your pc

**Comment by ZTW21** [comment]
![capture5](https://user-images.githubusercontent.com/37523643/37619724-ab329abe-2b90-11e8-89b9-5a5c47f22fc1.PNG)

Does this look right? I keep getting the same error

**Comment by maxenxe** [comment]
you should also change 'the result x' and the result y, so you take the bottom right coordinates - top left coordinates and this is what you should put instead of the result x and the result y

**Comment by ZTW21** [comment]
It was working perfectly, and then I did "npm start" again and it gave me a long string of HTML code and then this error.

![capture6](https://user-images.githubusercontent.com/37523643/37622716-d1663814-2b98-11e8-8bf6-d4e80bfd4179.PNG)

**Comment by ZTW21** [comment]
Update: I have fixed the previous error listed... But now I have a new problem. The questions and answers are resized properly and are being read, but instead of an answer, it gives me a Wikipedia link. How can I fix this?

**Comment by maxenxe** [comment]
This isn't an error, if it find a Wikipedia link, it'll say it and search for the answer on the page,if it doesn't find an answer, you'll know it because when it find one it says the answer " found" and if it find it on Wikipedia it'll say the answer " found on Wikipedia page "
