### ISSUE TITLE
Anyone can help me solve this error?

### ISSUE THREAD

**Issue by nanip9997** [maxenxe/HQ-Trivia-Bot#25]
I CANNOT GET THE QUESTION.JPG FILE BUT GETTING ANSWER.JPG AND THE COORDINATES IVE PALCED ARE NOT ACCURATE CAN ANY ONE HELP SOLVING AND MOREOVER I VE ADDED TESSERACT OCR TO MY PATH VARIABLES IT ADDS THAT I NEED TO ADD TESSDATA AND I EVEN ADDED IT TO MY ENVIRONEMNT PATH PLEASE ANY ONE SOLVE THIS CAN WAIT FOR SOLVING THIS [ISSUE
![capture2258](https://user-images.githubusercontent.com/29340053/37908995-57392bc0-3127-11e8-85b4-15bd8f301abd.PNG)
![capture2258](https://user-images.githubusercontent.com/29340053/37909029-71c0ed5c-3127-11e8-8dc9-d03abd24caee.PNG)

**Comment by yapal** [comment]
Copy n paste ur path here

**Comment by nanip9997** [comment]
Can you specify which one tesseract or graphics magik one ??

**Comment by yapal** [comment]
Which os are u using

**Comment by nanip9997** [comment]
Windows version bro

**Comment by nanip9997** [comment]
Bro is the bot working fine ??

**Comment by yapal** [comment]
Yes I have some issues yet but bot is working

**Comment by nanip9997** [comment]
Bro please explain it I cannot get it right Igot the code running fine it
takes the screen shot but it somehow don't get answers.jpg and question.jpg

Initially I thought tesseract cannot process the answers.jpg(as it is
executing first) and I have done various changes to my path but the error
remains as it is .

I've also tried another bot which includes python script but it cannot
install package modules from scratch and it is not working though.

So,please send me a detailed process on how to setup if you don't and only
if you have time or you can make a screen recording of how set the process
to work  and please make a video it would be very much helpful .

Thanks
Laxmikanth

On 28 Mar 2018 6:58 pm, "yapal" <notifications@github.com> wrote:

Yes I have some issues yet but bot is working

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/maxenxe/HQ-Trivia-Bot/issues/25#issuecomment-376886460>,
or mute the thread

**Comment by maxenxe** [comment]
https://www.youtube.com/watch?v=QzdqT0HTGLs
