### ISSUE TITLE
Google Blocking Requests

### ISSUE THREAD

**Issue by captinks** [maxenxe/HQ-Trivia-Bot#39]
Hey all, I'm using Mac Terminal to run this and everything was going good until google thought i was a robot and started blocking my IP address. Whenever I run this I get HTML spit back at me, Its a fun little captcha for me to solve except terminal does not run HTML. So I put it in an HTML file and opened it, it worked... kinda the HTML loads fine but the captcha say "Error for sight owner: invalid domain for sight key" So now I am stuck. Does anyone know how to get the captcha fixed?
---
![screen shot 2018-04-15 at 9 07 14 pm](https://user-images.githubusercontent.com/38414921/38789737-2ea93798-40f1-11e8-9dff-618533b59931.png)

**Comment by kiikoh** [comment]
yes this has also stumped me

**Comment by maxenxe** [comment]
There's no real solution to this, you can just try running the bot with a vpn
