### ISSUE TITLE
How to install tesseract-ocr 

### ISSUE THREAD

**Issue by GamerBrozRock** [maxenxe/HQ-Trivia-Bot#42]
how do you Install tesseract-ocr and add it to your PATH environment variable?

**Comment by HYaz0** [comment]
u go into Windows Config Panel and then into ur system
Control Panel\System and Security\System
then go into the advanced system settings
then environnement variables under advanced
then into system variables, ur gonna have to find path and add new and then paste the directory 
of tesseract-ocr .
for me its C:\Users\abcd\tesseract-ocr cuz I have it on my desktop and there it should work
