### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by wolfsquadron234** [maxenxe/HQ-Trivia-Bot#5]
![b878faf3b0773ca1769349b2047a9f2d](https://user-images.githubusercontent.com/37126529/37073076-9c979b7e-2192-11e8-82fc-917e73eec686.png)
I get this error when opening bot.js

**Comment by maxenxe** [comment]
To run a node js bot you must get in the script directory with a command prompt and type `node bot.js`

**Comment by wolfsquadron234** [comment]
im getting this now

Error: Could not execute GraphicsMagick/ImageMagick: gm "convert" "screenshot.jpg" "-crop" "351x233+606+334" "answers.jpg" this most likely means the gm/convert binaries can't be found
    at ChildProcess.<anonymous> (C:\Users\Desktop\HQ-Trivia-Bot-master\node_modules\gm\lib\command.js:232:12)
    at emitOne (events.js:116:13)
    at ChildProcess.emit (events.js:211:7)
    at ChildProcess.cp.emit (C:\Users\Desktop\HQ-Trivia-Bot-master\node_modules\cross-spawn\lib\enoent.js:36:37)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)

**Comment by maxenxe** [comment]
Please look at previous issues 😉

**Comment by wolfsquadron234** [comment]
i did however the link you provided was for mac

**Comment by maxenxe** [comment]
What did you added to your PATH on windows ?

**Comment by wolfsquadron234** [comment]
what do you mean by path? also im installing graphics magick to see if it works

**Comment by maxenxe** [comment]
There's a PATH field in you environment variables, the paths you put in are the paths your cmd will look to execute your commands

**Comment by wolfsquadron234** [comment]
where would i find environment variables? also after installing magick i got this

Screenshot done
Answers resized
node-tesseract: Running 'tesseract answers.jpg C:\Users\AppData\Local\Temp\tmp-7696XTtI7VD7bu61'
node-tesseract: Preprocessor cleanup
{ Error: Command failed: tesseract answers.jpg C:\Users\AppData\Local\Temp\tmp-7696XTtI7VD7bu61
'tesseract' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'tesseract answers.jpg C:\\Users\\AppData\\Local\\Temp\\tmp-7696XTtI7VD7bu61' }

**Comment by maxenxe** [comment]
Download this https://github.com/tesseract-ocr/tesseract/wiki/4.0-with-LSTM#400-alpha-for-windows
Then add these 2 paths to the Path system environmental variable ( Open Control Panel » System » Advanced » Environment Variables)
C:\Program Files (x86)\Tesseract-OCR
C:\Program Files (x86)\Tesseract-OCR\tessdata

**Comment by maxenxe** [comment]
Install the tesseract-ocr  exe and add this to your PATH:
;C:\Program Files (x86)\Tesseract-OCR;C:\Program Files (x86)\Tesseract-OCR\tessdata

Don't forget the first semicolon

**Comment by wolfsquadron234** [comment]
![d06933f92c6a3943adefb833ef4fdb9b](https://user-images.githubusercontent.com/37126529/37119375-2e1cded2-2225-11e8-9d8d-03001b79f10d.png)
it wont let me click ok till i add a value

**Comment by maxenxe** [comment]
You shouldn't create a new variable but add it to the existing PATH variable

**Comment by wolfsquadron234** [comment]
![7f0d984d099f184d61b044a92ab5318b](https://user-images.githubusercontent.com/37126529/37119556-c42f79d4-2225-11e8-9e05-4a2c10d6dd6e.png)
so it should like like this now

**Comment by maxenxe** [comment]
yes, sorry but you can remove the semicolon before the paths, I thought you where using Windows 7 but in Windows 10 you do not need the semicolon

**Comment by wolfsquadron234** [comment]
thank it works!

**Comment by maxenxe** [comment]
you're welcome 🙂

**Comment by wolfsquadron234** [comment]
question, what program did you use to find the cordinates

**Comment by maxenxe** [comment]
Didn't used it but http://www.adminsehow.com/wp-content/uploads/2012/03/MousePos.exe looks easy to use
