### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by iansquenet** [maxenxe/HQ-Trivia-Bot#50]
Error: Could not execute GraphicsMagick/ImageMagick: gm "convert" "screenshot.jpg" "-crop" "351x233+606+334" "answers.jpg" this most likely means the gm/convert binaries can't be found

**Comment by paramt** [comment]
I had this problem too, but it can be resolved very easily. You just need to add `C:\Program Files\GraphicsMagick-1.3.29-Q16` (or wherever GraphicsMagick was installed) to your PATH variables.

On Windows 10, you can do that by going to:

Control Panel > System and Security > System > Advanced system settings > Advanced > Environment variables > PATH > New
