### ISSUE TITLE
it doesnt google the answer , no problem appears

### ISSUE THREAD

**Issue by houssemdza** [maxenxe/HQ-Trivia-Bot#56]
i downloaded the bot , everytyhing is set when i launch the bot i get the question and the answer but id doesnt google the answer , no problem appears 
pic for the problem
https://ibb.co/eMHOyT

**Comment by maxenxe** [comment]
It's because it doesn't detect 3 answers but 2, and it's normal because it only reads text writen in a black font, I'm pretty sure that if you use a different image with no answer selected it'll work

**Comment by houssemdza** [comment]
yeah i didnt notice , after fixing that i got this problem that i dont find a solution to ! 
 if(link.title.indexOf(answers[1]) != -1) {
                                        ^
TypeError: Cannot read property 'title' of undefined
