### ISSUE TITLE
Coordinates Help

### ISSUE THREAD

**Issue by Helpme0822** [maxenxe/HQ-Trivia-Bot#6]
I entered the right coordinates like it was told in the description but i only get 1/4 of the question on the screenshot why?

**Comment by maxenxe** [comment]
Can you paste here your coordinates ?

**Comment by Helpme0822** [comment]
top left (486;108)
bottom right (853;209)
result (367;101)

**Comment by maxenxe** [comment]
How did you write them in the code ?

**Comment by Helpme0822** [comment]
![123](https://user-images.githubusercontent.com/36854248/37240820-b2ed883c-2450-11e8-92c9-15e0e2f0d363.png)
Like that I also wrote that in line 19 like you told

**Comment by maxenxe** [comment]
Line 19, you should put the coordinates for the answers and at line 34 it's for the question.
Also, the coordinates should be .crop(top-left,result)
top-left is the top-left coordinates for the question or for the answers

**Comment by Helpme0822** [comment]
oh okay but i did do (top-left,result) or didn't I?

**Comment by maxenxe** [comment]
I think you did but not with the coordinates in your second answer to this issue

**Comment by Helpme0822** [comment]
I did do it with the coordinates from my second answer or did i understand something wrong? could you please write how it should be written with my coordinates please?

**Comment by maxenxe** [comment]
Your result in second answer is not the same in your code

**Comment by Helpme0822** [comment]
oh yeah i know but also with the right result it didn't work that's why i used other numbers to try if it would maybe work then but even with the right numbers it still screenshots another part of the screen

**Comment by maxenxe** [comment]
Is the screenshot file full screen ?

**Comment by Helpme0822** [comment]
yes

**Comment by maxenxe** [comment]
There's a problem with the coordinates but I don't know what's the problem, how did you got the coordinates ?

**Comment by Helpme0822** [comment]
i used an app that i downloaded on the internet and then because it didn't work i saw that you posted a link for an app on an issue so i used that and both told me the same coordinates

**Comment by maxenxe** [comment]
How does the answers.jpg and question.jpg file looks like ?

**Comment by Helpme0822** [comment]
![question](https://user-images.githubusercontent.com/36854248/37245341-c943a364-2496-11e8-8d17-3694f925460d.jpg)
![answers](https://user-images.githubusercontent.com/36854248/37245342-cde35cac-2496-11e8-86de-b162684a9d1a.jpg)
they look like that btw i'm using another app than hq trivia it's a french app

**Comment by maxenxe** [comment]
Do you speak French? Try increasing values from result coordinates

**Comment by Helpme0822** [comment]
yes i do and increase them by how much?

**Comment by maxenxe** [comment]
Ça va être plus facile de parler en français ahaha, teste avec 100 ou 200 chacune

**Comment by Helpme0822** [comment]
ok je vais essayer tu veux que je renvoie apres a nouveau les fichiers .jpg?

**Comment by maxenxe** [comment]
Non non pas besoin

**Comment by Helpme0822** [comment]
ca s'est un peu ameliorer pour les reponses mais ce n'est pas encore parfait et pour la question ca ne s'est pas ameliorer du tout

**Comment by Helpme0822** [comment]
le probleme est plus avec l'hauteur de l'image

**Comment by maxenxe** [comment]
En fait les coordonnées sont traduites comme ça : (endroit de départ horizontal, endroit de départ vertical, largeur depuis l'endroit de départ horizontal, hauteur depuis l'endroit de départ vertical) gère les coordonnées et vois si ça s'améliore

**Comment by Helpme0822** [comment]
comment je fais pour modifier la grandeur de l'image?

**Comment by Helpme0822** [comment]
car en modifiant l'y ca bouge seulement de haut en bas mais ca n'agrandit pas l'image

**Comment by maxenxe** [comment]
À la ligne 19, par exemple, tu as .crop(a,b,c,d) 
Il faut augmenter la valeur de c et d

**Comment by Helpme0822** [comment]
oui je sais mais en augementat d la hauteur de l'image ne devient pas plus haute mais ca bouge seulement vers le haut je sais pas trop comment expliquer

**Comment by maxenxe** [comment]
Si tu diminues b et augmentes d, il se passe quoi ?

**Comment by maxenxe** [comment]
Erreur de ma part, essaye d'écrire (c,d,a,b) :)

**Comment by shabbir1215** [comment]
I have a little issue with (c, d, a, b)  a & b since it is not working properly. Increasing b is just making the image cropping widder even though it's suppose to make it gain more height

**Comment by Helpme0822** [comment]
apres avoir finalement reussi d'avoir les bonnes proportions pour les images je recoit ca: 
Screenshot done
Answers resized
node-tesseract: Running 'tesseract answers.jpg C:\Users\dylri\AppData\Local\Temp
\tmp-8472JFW7o8tbeRcz'
node-tesseract: Deleting 'C:\Users\dylri\AppData\Local\Temp\tmp-8472JFW7o8tbeRcz
.txt'
node-tesseract: Preprocessor cleanup
Question resized
node-tesseract: Running 'tesseract question.jpg C:\Users\dylri\AppData\Local\Tem
p\tmp-84728Ks4mI1gm73p'
node-tesseract: Deleting 'C:\Users\dylri\AppData\Local\Temp\tmp-84728Ks4mI1gm73p
.txt'
node-tesseract: Preprocessor cleanup
The question is "3. Quel surnom est donné aux  soldats de la premiére guerre mon
diale ?  "
Wikipedia link found: https://fr.wikipedia.org/wiki/Poilu
Wikipedia link found: https://fr.wikipedia.org/wiki/Appellations_de_la_Premi%C3%
A8re_Guerre_mondiale
Wikipedia link found: https://fr.wikipedia.org/wiki/Tommy_(soldat)
C:\Users\dylri\Desktop\HQ-Trivia-Bot-master\bot.js:58
                                        if($('body').text().toLowerCase().indexO
f(answers[0].toLowerCase()) != -1) {

             ^

TypeError: Cannot read property 'toLowerCase' of undefined
    at Request._callback (C:\Users\dylri\Desktop\HQ-Trivia-Bot-master\bot.js:58:
94)
    at Request.self.callback (C:\Users\dylri\Desktop\HQ-Trivia-Bot-master\node_m
odules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\dylri\Desktop\HQ-Trivia-Bot-master\node_mod
ules\request\request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\dylri\Desktop\HQ-Trivia-Bot-master\
node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)

a la fin il y a une sorte d'erreur que dois-je faire pour l'enlever?

**Comment by maxenxe** [comment]
Est ce que answers.jpg est bon ? 
Si oui c'est tesseract qui ne sait pas lire

**Comment by Helpme0822** [comment]
oui answers.jpg est bon donc ca ne marche pas avec cette app?

**Comment by maxenxe** [comment]
Je vais me renseigner

**Comment by Helpme0822** [comment]
ok merci tu veux que je te donne le nom de l'app ou tu la connais deja ou tu n'as pas besoin?

**Comment by maxenxe** [comment]
Oui je veux bien

**Comment by Helpme0822** [comment]
flashbreak

**Comment by Helpme0822** [comment]
tu peux aussi voir des replays sur youtube en cherchant flashbreak comme ca tu pourras tester sur les replays

**Comment by Helpme0822** [comment]
ecrit sur ce post stp si tu trouve une soltution

**Comment by maxenxe** [comment]
Je pense appliquer un filtre sur l'image mais c'est sur que ça marche

**Comment by Helpme0822** [comment]
c'est sur ou c'est pas sur?

**Comment by maxenxe** [comment]
pas sûr *

**Comment by Helpme0822** [comment]
et donc pas de progres?

**Comment by maxenxe** [comment]
non la je suis pas chez moi ducoup je peux pas bosser dessus

**Comment by Helpme0822** [comment]
ah oke sinon si tu veux tu peux peut etre m’expliquer comment mettre un filtre sur la photo et j’essaierait moi meme

**Comment by Helpme0822** [comment]
Donc tu as trouvé une solution?

**Comment by maxenxe** [comment]
Non mais je pense que ça va être compliqué de faire tt le travail sur l'image + le recherche Google en 10 secondes

**Comment by Helpme0822** [comment]
oke et y a t'il une methode pour faire cette methode plus rapide car sur hq trivia ca dure aussi plus longtemps que 12 secondes et je trouve aussi que ca dure jusqu'a que ca fait un screenshot ca ne fait pas tout de suite un screenshot apres qu'on entre node bot.js ca dure toujours un moment et ensuite ca fait un screenshot

**Comment by maxenxe** [comment]
Peut être en refactorisant le code, il y a des sites pour faire ça il me semble

**Comment by Helpme0822** [comment]
peux-tu le faire stp? ou sinon explique moi comment il faut le faire stp

**Comment by maxenxe** [comment]
var screenshot=require("desktop-screenshot"),gm=require("gm"),nodecr=require("nodecr"),google=require("google"),request=require("request"),cheerio=require("cheerio"),question,answers,pointsAnswer0,pointsAnswer1,pointsAnswer2;screenshot("screenshot.jpg",{width:1600},function(e){e?console.log("Screenshot failed",e):console.log("Screenshot done"),gm("screenshot.jpg").crop("351","233","606","334").write("answers.jpg",function(e){e?console.log(e):(console.log("Answers resized"),nodecr.process("answers.jpg",function(e,o){if(e)console.error(e);else{answers=o.replace(/^\s*$[\n\r]{1,}/gm,""),answers=answers.split(/\n/g),answers=answers.filter(function(e){return 0===e||e});for(var s=0;s<answers.length;s++)console.log(answers[s]);gm("screenshot.jpg").crop("389","200","587","198").write("question.jpg",function(e){e?console.log(e):(console.log("Question resized"),nodecr.process("question.jpg",function(e,o){if(e)console.error(e);else{question=o.replace(/\n/g," "),console.log('The question is "'+question+'"'),google.resultsPerPage=25;var s=0;google(question,function(e,o){e&&console.error(e);for(var n=0;n<o.links.length;++n){var r=o.links[n];null!=r.link&&-1!=r.link.indexOf("wikipedia")&&(console.log("Wikipedia link found: "+r.link),request(r.link,function(e,o,s){if(e)console.log("Error: "+e);else{var n=cheerio.load(s);-1!=n("body").text().toLowerCase().indexOf(answers[0].toLowerCase())&&(console.log(answers[0]+" found in Wikipedia page!"),pointsAnswer0++),-1!=n("body").text().toLowerCase().indexOf(answers[1].toLowerCase())&&(console.log(answers[1]+" found in Wikipedia page!"),pointsAnswer1++),-1!=n("body").text().toLowerCase().indexOf(answers[2].toLowerCase())&&(console.log(answers[2]+" found in Wikipedia page!"),pointsAnswer2++)}})),-1!=r.title.indexOf(answers[0])&&(pointsAnswer0++,console.log(answers[0]+" found!")),-1!=r.title.indexOf(answers[1])&&(pointsAnswer1++,console.log(answers[1]+" found!")),-1!=r.title.indexOf(answers[2])&&(pointsAnswer2++,console.log(answers[2]+" found!")),-1!=r.description.indexOf(answers[0])&&(pointsAnswer0++,console.log(answers[0]+" found!")),-1!=r.description.indexOf(answers[1])&&(pointsAnswer1++,console.log(answers[1]+" found!")),-1!=r.description.indexOf(answers[2])&&(pointsAnswer2++,console.log(answers[2]+" found!"))}4>s&&(s+=1,o.next&&o.next())})}}))})}}))})});

**Comment by maxenxe** [comment]
remplace le code de bot.js par ça

**Comment by maxenxe** [comment]
en changeant les coordonnées

**Comment by Helpme0822** [comment]
chaque ligne dans une differente ligne ou tout dans une ligne?

**Comment by maxenxe** [comment]
Tu peux tout mettre dans une même ligne mais si ça le fait pas de base c'est pas grave c'est pas une grosse perte de performances

**Comment by Helpme0822** [comment]
pour moi il y a pas d'ameliorations dans la duree

**Comment by maxenxe** [comment]
Je peux rien faire alors désolé

**Comment by Helpme0822** [comment]
oke merci quand meme
