### ISSUE TITLE
Tesseract not recognised

### ISSUE THREAD

**Issue by Darwin1119** [maxenxe/HQ-Trivia-Bot#7]
When I run the bot, I receive an error telling me tesseract is not a recognized command.
Here is what command prompt gives me.

C:\Users\landw>node bot.js
Screenshot done
Answers resized
node-tesseract: Running 'tesseract answers.jpg C:\Users\landw\AppData\Local\Temp\tmp-15148a3kNbjtP5mlX'
node-tesseract: Preprocessor cleanup
{ Error: Command failed: tesseract answers.jpg C:\Users\landw\AppData\Local\Temp\tmp-15148a3kNbjtP5mlX
'tesseract' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'tesseract answers.jpg C:\\Users\\landw\\AppData\\Local\\Temp\\tmp-15148a3kNbjtP5mlX' }

**Comment by maxenxe** [comment]
Rereading the readme.md will probably fix your problem (updated it yesterday)

**Comment by Darwin1119** [comment]
Still facing the same problem. What else could be the issue?

**Comment by maxenxe** [comment]
Tesseract should be recognized if it's in PATH, try restarting your PC maybe

**Comment by Darwin1119** [comment]
I restarted my computer and it's still saying the same thing. I put tesseract in the user variables. is that the right one?

**Comment by maxenxe** [comment]
In your environment variables, you have normally the PATH variable, you must just add `;C:\Program Files (x86)\Tesseract-OCR;C:\Program Files (x86)\Tesseract-OCR\tessdata` to it

**Comment by Darwin1119** [comment]
just added it to there and I'm getting the same thing

**Comment by maxenxe** [comment]
Can you paste here your PATH ?

**Comment by Darwin1119** [comment]
https://gyazo.com/411fad8511f05e1dc3bc945ee84df736

**Comment by Darwin1119** [comment]
did that and the issue persists. Could I have installed it wrong somehow?

**Comment by maxenxe** [comment]
Did you relaunched your cmd ? Because you have to restart it everytime you change your Path
It's weird, check if the directory added into Path exists and if they exists then check if tesseract.exe is in one of them

**Comment by Darwin1119** [comment]
C:\Program Files (x86)>cd Tesseract-OCR
The system cannot find the path specified.

**Comment by maxenxe** [comment]
Install this and retry https://github.com/tesseract-ocr/tesseract/wiki/4.0-with-LSTM#400-alpha-for-windows

**Comment by Darwin1119** [comment]
Got it! thank you for your help!

**Comment by Darwin1119** [comment]
I am now having an issue with the cropping of the screenshots, when it crops, it seems to read both the answers and the question for the question as well as read it all for the answers

**Comment by maxenxe** [comment]
https://github.com/maxenxe/HQ-Trivia-Bot/issues/6

**Comment by maxenxe** [comment]
Any news ?

**Comment by Darwin1119** [comment]
It's working perfectly, but Google asks it to fill out a captcha or something after 15 ish requests

**Comment by Darwin1119** [comment]
I just had to play with the cropping and adjust with trial and error but its working good

**Comment by maxenxe** [comment]
Nice !

**Comment by beannguyen** [comment]
Add C:\Program Files (x86)\Tesseract-OCR to PATH,
and 
TESSDATA_PREFIX = C:\Program Files (x86)\Tesseract-OCR\tessdata

It's worked for me.
